### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by ShevT** [adil192/saber#255]
**Describe the bug**
The program crashes on exit.

**To Reproduce**
1. Ыtart program
2. Exit the program

**Logcat**
```
01-20 09:48:49.231 29351 29351 E AndroidRuntime: FATAL EXCEPTION: main
01-20 09:48:49.231 29351 29351 E AndroidRuntime: Process: com.adilhanney.saber, PID: 29351
01-20 09:48:49.231 29351 29351 E AndroidRuntime: kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at com.TDTxLE.open_as_default.OpenAsDefaultPlugin.onDetachedFromActivity(Unknown Source:21)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at io.flutter.embedding.engine.a.detachFromActivity(SourceFile:34)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.r(SourceFile:59)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at io.flutter.embedding.android.FlutterActivity.onDestroy(SourceFile:19)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.app.Activity.performDestroy(Activity.java:8562)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1458)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5396)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5442)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7872)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-20 09:48:49.231 29351 29351 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

**Device (please complete the following information):**
 - Device: [OnePlus 7T Pro]
 - OS: [Android 13]
 - Version: [e.g. v0.5.7]

**Comment by adil192** [comment]
Reproduced on Android emulator:
```log
D/AndroidRuntime(20811): Shutting down VM
E/AndroidRuntime(20811): FATAL EXCEPTION: main
E/AndroidRuntime(20811): Process: com.adilhanney.saber, PID: 20811
E/AndroidRuntime(20811): kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
E/AndroidRuntime(20811): 	at com.TDTxLE.open_as_default.OpenAsDefaultPlugin.onDetachedFromActivity(OpenAsDefaultPlugin.kt:92)
E/AndroidRuntime(20811): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:383)
E/AndroidRuntime(20811): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:686)
E/AndroidRuntime(20811): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:715)
E/AndroidRuntime(20811): 	at android.app.Activity.performDestroy(Activity.java:8319)
E/AndroidRuntime(20811): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1376)
E/AndroidRuntime(20811): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5413)
E/AndroidRuntime(20811): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5459)
E/AndroidRuntime(20811): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
E/AndroidRuntime(20811): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(20811): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(20811): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(20811): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
E/AndroidRuntime(20811): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20811): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(20811): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(20811): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(20811): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20811): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(20811): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process (20811): Sending signal. PID: 20811 SIG: 9
Lost connection to device.
```
