### ISSUE TITLE
Illegal argument in isolate message: object is unsendable

### ISSUE THREAD

**Issue by adil192** [adil192/saber#638]
### Describe the bug

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' Class: _Future@4048458 (see restrictions listed at `SendPort.send()` documentation for more information)
 <- Instance of 'Editor' (from package:saber/pages/editor/editor.dart)
 <- Instance of 'EditorState' (from package:saber/pages/editor/editor.dart)
 <- Context num_variables: 1
 <- Closure: () => void from Function 'autosaveAfterDelay':. (from dart:core)
 <- Instance of 'EditorImage' (from package:saber/components/canvas/_editor_image.dart)
 <- Context num_variables: 2
 <- Closure: () => Uint8List? (from dart:core)

#0      _SendPort._sendInternal (dart:isolate-patch/isolate_patch.dart:249:43)
#1      _SendPort.send (dart:isolate-patch/isolate_patch.dart:230:5)
#2      WorkerImpl.work (package:worker_manager/src/worker/worker_io.dart:66:15)
<asynchronous suspension>
#3      _Executor._schedule.<anonymous closure> (package:worker_manager/src/scheduling/executor.dart:112:37)
<asynchronous suspension>
```

> (see restrictions listed at [`SendPort.send()`](https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html) documentation for more information)

### To reproduce

TBD

### Expected behavior

No exception

### Saber version

v0.12.3 DIRTY (46147c92c790b9438f9f51c9feb547bd78394443)

### Device

- Device: Google Pixel 6 Pro
- OS: Android 13

### Anything else?

This is after updating to Flutter 3.10 and worker_manager 6

**Comment by adil192** [comment]
The exception is now
```dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)]\
 Unhandled Exception: Invalid argument(s): Illegal argument in isolate message:\
 object is unsendable - Library:'dart:ui' Class: _Image@15065589\
 (see restrictions listed at `SendPort.send()` documentation for more information)\

 <- Instance of 'Image' (from dart:ui)
 <- Instance of 'EditorImage' (from package:saber/components/canvas/_editor_image.dart)
 <- Context num_variables: 2
 <- Closure: () => Uint8List? (from dart:core)

#0      _SendPort._sendInternal (dart:isolate-patch/isolate_patch.dart:249:43)
#1      _SendPort.send (dart:isolate-patch/isolate_patch.dart:230:5)
#2      WorkerImpl.work (package:worker_manager/src/worker/worker_io.dart:66:15)
<asynchronous suspension>
#3      _Executor._schedule.<anonymous closure> (package:worker_manager/src/scheduling/executor.dart:112:37)
<asynchronous suspension>

```
