### ISSUE TITLE
Logged out after closing app on Manjaro KDE

### ISSUE THREAD

**Issue by MisterCcobD** [adil192/saber#826]
### Describe the bug

Saber notes, dos not keep you logged in.
On desktop app, i have to enter the credentials and log in every time i open the app.

### To reproduce

open saber
log in
close saber
open again and see if you still logged in

### Expected behavior

https://github.com/adil192/saber/assets/126014590/8917c57f-4117-49ba-b664-31cbdf2622d8

### Saber version

0.14.6(14060)

### Device

- Device:Lenovo 15 arh 05
- OS: Manjaro KDE

**Comment by ceskyDJ** [comment]
Hmm, it's definitely a bug. It should keep the login session. What version do you need (Arch package, AppImage, Snap, …)?

**Comment by MisterCcobD** [comment]
Using on Manjaro KDE
Installed Saber 0.14.6 via Flathub
  Desktop: KDE Plasma v: 5.27.5 tk: Qt v: 5.15.9 wm: kwin_x11 vt: 1 dm: SDDM
    Distro: Manjaro Linux base: Arch Linux
  Kernel: 6.1.31-2-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 13.1.1

**Comment by ceskyDJ** [comment]
Did you try another sources (e.g. AppImage should be pretty simple to try)?

**Comment by MisterCcobD** [comment]
i could try, i see an appimage in the ui software installer but giver an error and idk how to buid from .yml myself

**Comment by ceskyDJ** [comment]
I have Debian, so I just downloaded the AppImage file from releases, and it could be run from CLI like a script (after giving it proper permission). Manjaro doesn't support this way?

**Comment by ceskyDJ** [comment]
It should work, see https://itsfoss.com/use-appimage-linux/, https://forum.manjaro.org/t/how-to-use-appimage-on-manjaro-arch-based-linux/34375, etc.

**Comment by adil192** [comment]
@MisterCcobD Do you have gnome-keyring or ksecretservice installed?

**Comment by MisterCcobD** [comment]
Latest verson (0.15.2) on Manjaro , still dosn't keep login session.
No i don't have gnome-keyring or ksecretsservice

**Comment by adil192** [comment]
> Latest verson (0.15.2) on Manjaro , still dosn't keep login session.
> No i don't have gnome-keyring or ksecretsservice

You need one of them for [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) to work

**Comment by MisterCcobD** [comment]
i understand nothing bro, i got no experience with mobile apps

**Comment by adil192** [comment]
Follow the `1 Installing` section from https://wiki.archlinux.org/title/GNOME/Keyring

**Comment by MisterCcobD** [comment]
On the other hand, should't just work? Caz KDE has it's own  app for secret service interface, or it really needs Keyrings just for the way it works within systemD?

**Comment by adil192** [comment]
Are you referring to [ksecretsservice](https://community.kde.org/KDE_Utils/ksecretsservice)?

It should just work with most distros ([flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) uses [libsecret](https://wiki.gnome.org/Projects/Libsecret))

**Comment by MisterCcobD** [comment]
I have them both, first i thought ksecretsservice needs libsecret but is a different library and still doesn't keep me logged in.
one option is to try with gnome-keyring and see what happens, but i'm skeptical...what if i break something related to ksecretservice?

**Comment by oa01** [comment]
I am on Arch
Installed Saber via Flatpak (version 0.15.3)
Same Issue, libsecret is installed (libsecret-0.21.0-1)

**Comment by MisterCcobD** [comment]
> I am on Arch Installed Saber via Flatpak (version 0.15.3) Same Issue, libsecret is installed (libsecret-0.21.0-1)
> 
> Edit: I've tried it with the AppImage and it also does not keep the session

Does it sync your notes?
Mine doesn't sync anymore

**Comment by ceskyDJ** [comment]
> Edit: I've tried it with the AppImage and it also does not keep the session

Did you try to run it via terminal and look at logs in there?

**Comment by MisterCcobD** [comment]
Ok, done something:
updated saber on my phone, now synched but on desktop it shows me a banner that says ' read only, this note was edited on a newer version of saber ' , i searched for the installer and it says is up to date, even with command it says is already installed
I opened with konsole and the logs are these:
```

(saber:2): Gtk-WARNING **: 18:54:39.081: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 18:54:39.082: Failed to load module "xapp-gtk3-module"
Gtk-Message: 18:54:39.082: Failed to load module "canberra-gtk-module"

(saber:2): Gdk-CRITICAL **: 18:54:39.125: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

** (saber:2): CRITICAL **: 18:54:39.231: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (saber:2): CRITICAL **: 18:54:39.234: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (saber:2): CRITICAL **: 18:54:39.237: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (saber:2): CRITICAL **: 18:54:39.239: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (saber:2): CRITICAL **: 18:54:39.242: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (saber:2): WARNING **: 18:54:39.383: libsecret_error: \u000c@\xe9\xf0\u0007
flutter: SEVERE: Prefs: Error loading allowInsecureConnections: FormatException: Missing extension byte (at offset 3)

** (saber:2): WARNING **: 18:54:39.390: libsecret_error: \u000c@\xe9\xf0\u0007
flutter: SEVERE: Prefs: Error loading url: FormatException: Missing extension byte (at offset 3)

** (saber:2): WARNING **: 18:54:39.397: libsecret_error: \xf7q=
\xa2U
flutter: SEVERE: Prefs: Error loading username: FormatException: Missing extension byte (at offset 2)

** (saber:2): WARNING **: 18:54:39.403: libsecret_error: \u000c@\xe9\xf0\u0007
flutter: SEVERE: Prefs: Error loading ncPassword: FormatException: Missing extension byte (at offset 3)

** (saber:2): WARNING **: 18:54:39.408: libsecret_error: \u000c@\xe9\xf0\u0007
flutter: SEVERE: Prefs: Error loading encPassword: FormatException: Missing extension byte (at offset 3)

** (saber:2): WARNING **: 18:54:39.412: libsecret_error: \u000b@\xe9\xf0\u0007
flutter: SEVERE: Prefs: Error loading key: FormatException: Missing extension byte (at offset 3)

** (saber:2): WARNING **: 18:54:39.417: libsecret_error: -\xf0\xe9d     \u007f
flutter: SEVERE: Prefs: Error loading iv: FormatException: Missing extension byte (at offset 2)
flutter: dynamic_color: Accent color detected.

** (saber:2): WARNING **: 18:55:04.247: atk-bridge: get_device_events_reply: unknown signature
^C

```

**Comment by MisterCcobD** [comment]
Now just synched on mobile again and seems fine...updated text written on desktop

**Comment by ceskyDJ** [comment]
> i searched for the installer and it says is up to date, even with command it says is already installed
What kind of installer do you mean — pacman?

> ' read only, this note was edited on a newer version of saber ' 
Does this error occur even for newest available AppImage?

**Comment by ceskyDJ** [comment]
@adil192, there are obviously some problems with libsecret (as logs have shown). Could you look at it, please?

**Comment by MisterCcobD** [comment]
> @adil192, there are obviously some problems with libsecret (as logs have shown). Could you look at it, please?

i've found some difference in kwallet contents of saber aplication
searching for saber shows zero content but checking listings it shows (1)

**Comment by diolwe** [comment]
````
** (saber:2): WARNING **: 13:23:00.069: libsecret_error: \u000bA\xa5\xe0\xb9U

** (saber:2): WARNING **: 13:23:00.071: libsecret_error: \u000c@\x91\xf4\u0007
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 2)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:503)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#6      EncPref._save (package:saber/data/prefs.dart:500)
<asynchronous suspension>
````
I'm on Manjaro and seem to have the same problem: on closing the flatpak desktop app I get logged out. libsecret is installed
(version is 0.21.0-1). Nextcloud is up2date: 
![ksnip_20231004-132933](https://github.com/adil192/saber/assets/907156/50f45592-fc11-457f-b98a-3eb5ec4fefa4)

Might be part of the problem: I can sync notes from Android to Desktop but not into the other direction.

**Comment by diolwe** [comment]
I switched away from the Flatpak and now use the AppImage - which remembers the login into my NC on Manjaro.

**Comment by MisterCcobD** [comment]
> I switched away from the Flatpak and now use the AppImage - which remembers the login into my NC on Manjaro.

I tried with appimages at the time...didn't worked.
Maybe i'll tay again some updates later, and if is cool, i'll give a big coffe
