### ISSUE TITLE
Unable to log from multiple devices on self-hosted nextcloud

### ISSUE THREAD

**Issue by bestlibre** [adil192/saber#943]
### Describe the bug

I'm unable to log from multiple devices on my nextcloud instance. The first device log in fine, but as soon as a saber folder exist, the following ones are unable to log.

If I log out from a session and try to log back in from the same device it fails with the same error.

### To reproduce

1. Log from one device
2. Try to log with another one

### Expected behavior

I should be able to log from multiple devices to use the sync feature

### Saber version

v0.16.1

### Device

- Device: Google Pixel 6
- OS: Android 13
- Saber Version: playstore (16.1) or F-Droid (15.5)

- Device: PC
- OS: Debian 11
- Saber Version: Flatpack

- Device: Steam Deck
- OS: SteamOS
- Saber Version: Flatpack

### Anything else?

I have use nextcloud scan as requested :
![image](https://github.com/adil192/saber/assets/621360/c8063a9b-1666-498e-ad6d-af5881b035a7)

Here are the log from my PC with a failing session :
```
** (saber:2): WARNING **: 12:02:17.072: libsecret_error: \u001d\x87ZT\u0002\u007f
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 1)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:503)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#6      EncPref._save (package:saber/data/prefs.dart:500)
<asynchronous suspension>

flutter: SEVERE: _NcLoginPageState: Failed to load encryption key: FormatException: Unexpected end of input (at character 1)

^


** (saber:2): WARNING **: 12:02:17.326: libsecret_error: rET\xf0\u0007
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Missing extension byte (at offset 4)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:503)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#6      EncPref._save (package:saber/data/prefs.dart:500)
<asynchronous suspension>
```

**Comment by strk** [comment]
Duplicated of #923 ?

**Comment by bestlibre** [comment]
> Duplicated of #923 ?

I'm not sure. The linked issue speak of a problem of synchronization, not of an impossibility to log from multiple devices. As I understand it, the author is able to log but nothing is synchronized. I'm unable to log after the first connection.

**Comment by losetsinn** [comment]
Same Bug Here. Log in on my nextcloudserver with 0.17.1 with a Galaxy Tab 9.
(Saber Direktory is create in Nextcloud)
Without make any Changes or create notes IT IS Not posible to log in on a S23 with Same fdroid Version.

**Comment by gitwas** [comment]
Just to chime in that I am seeing similar behaviour:

Server scan:
- Rating A
- Running Nextcloud 25.0.1.1
- NOT on latest patch level
- Major version still supported

Device:
- Galaxy Tab S3 SM-T825
- Android version 11
- Lineage 18.1 gts3llte
- Saber version 18.1 (from Github repo)

Desktop:
- Ubuntu 20.04
- Saber version v0.18.0 (from snap)

It does appear to matter which order things are done.

Steps taken:

1. Deleted the Saber folder from my Nextcloud instance, 
2. revoked all relevant session permissions (for Android app and Desktop app).
3. created new app password in Nextcloud 
4. entered details in Android app
5. RESULT - Could see new folder in Nextcloud
6. Entered details into Desktop app
7. RESULT - login error in desktop app
`
flutter: SEVERE: _NcLoginPageState: Failed to load encryption key: FormatException: Unexpected end of input (at character 1)
`
9. created separate App password for desktop app
10. RESULT - login error in desktop app
11. deleted folder from Nextcloud
12. re-entered details in desktop app
13. RESULT: desktop app logged in, android app stayed logged in

Notes are saved up to nextcloud (but at zero size, which I understand to be a known bug), but desktop notes cannot be seen by android, and vice versa.


`
flutter: SEVERE: FileSyncer: Failed to add b9425e321a0a9470963638b91e864f1490e370460c1406bfbb78b8b70f102bf6.sbe to download queue: Invalid argument(s): Invalid or corrupted pad block
flutter: WARNING: FileSyncer: startSync: Failed to download 0 files
`

**Comment by Appel-flappen** [comment]
Also getting same error with key, however this is with official (saber) nextcloud instance.
When downloading and looking at the config.sbc file in the Saber directory, they show completely different keys and "iv" even though the encryption password was the same when logging in from the android phone and the linux desktop. 
v0.21.4 on both phone and desktop.
